"""criando tabela camisa

Revision ID: 984d7fca0d5f
Revises: bfa6d9e8c3a4
Create Date: 2026-06-24 10:40:57.130908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984d7fca0d5f'
down_revision = 'bfa6d9e8c3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camisa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tamanho', sa.String(length=10), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camisa')
    # ### end Alembic commands ###
